version: '3.4'

services:
  app:
    build: .
    depends_on:
     - db
    volumes:
      - ./:/app
    environment:
      FOOBAR: bar
    env_file:
      - .env
    command: /app/my-app

  db:
    image: postgres:10-alpine

  redis:
    image: redis:alpine
